<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.1-dev INSTALLER - Sunday 30th of March 2014 03:26:26 PM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://local.referowl.com/hybridauth/hybridauth/",

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => true
			),

			"AOL"  => array ( 
				"enabled" => true 
			),

			"Yahoo" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "dj0yJmk9RWt1Q3Ywb01kdU01JmQ9WVdrOWVuSlJTVE16TjJVbWNHbzlNVEkwTXpNeE5qYzJNZy0tJnM9Y29uc3VtZXJzZWNyZXQmeD03Yg--", "secret" => "cb7c52b0e9200576eb7171854a67761b6c772144" )
			),

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "586573025089-ecprfl2c03riupbab99ji9hmju1i12b7.apps.googleusercontent.com", "secret" => "oN4v1BxrXPew81rlquPM7Nbd" )
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "000000004010E7F6", "secret" => "Qkz01xbN5dBeZ8EZLI8lQsJTssKO9mFr" ) 
			),

			"MySpace" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"Foursquare" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

            "Plaxo" => array (
                "enabled" => true,
                "keys"    => array ( "key" => "anonymous", "secret" => "" )
            ),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
